// Package athena_workflow provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.0.0 DO NOT EDIT.
package athena_workflow

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

const (
	Sigv4Scopes = "sigv4.Scopes"
)

// RunAthenaQueryTemplateRequest defines model for RunAthenaQueryTemplateRequest.
type RunAthenaQueryTemplateRequest struct {
	Athena struct {
		Catalogue string `json:"catalogue"`
		Database  string `json:"database"`
		Workgroup string `json:"workgroup"`
	} `json:"athena"`
	Parameters    map[string]interface{} `json:"parameters"`
	QueryTemplate string                 `json:"query_template"`
}

// RunAthenaQueryTemplateResponse defines model for RunAthenaQueryTemplateResponse.
type RunAthenaQueryTemplateResponse struct {
	QueryExecutionId    string `json:"query_execution_id"`
	QueryExecutionState string `json:"query_execution_state"`
	ResultPath          string `json:"result_path"`
}

// RunS3AthenaQueryTemplateRequest defines model for RunS3AthenaQueryTemplateRequest.
type RunS3AthenaQueryTemplateRequest struct {
	Athena struct {
		Catalogue string `json:"catalogue"`
		Database  string `json:"database"`
		Workgroup string `json:"workgroup"`
	} `json:"athena"`
	Parameters      map[string]interface{} `json:"parameters"`
	S3QueryTemplate struct {
		Bucket string `json:"bucket"`
		Key    string `json:"key"`
	} `json:"s3_query_template"`
}

// RunAthenaQueryTemplateJSONRequestBody defines body for RunAthenaQueryTemplate for application/json ContentType.
type RunAthenaQueryTemplateJSONRequestBody = RunAthenaQueryTemplateRequest

// RunS3AthenaQueryTemplateJSONRequestBody defines body for RunS3AthenaQueryTemplate for application/json ContentType.
type RunS3AthenaQueryTemplateJSONRequestBody = RunS3AthenaQueryTemplateRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /athena/run_query_template)
	RunAthenaQueryTemplate(ctx echo.Context) error

	// (POST /athena/run_s3_query_template)
	RunS3AthenaQueryTemplate(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// RunAthenaQueryTemplate converts echo context to params.
func (w *ServerInterfaceWrapper) RunAthenaQueryTemplate(ctx echo.Context) error {
	var err error

	ctx.Set(Sigv4Scopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.RunAthenaQueryTemplate(ctx)
	return err
}

// RunS3AthenaQueryTemplate converts echo context to params.
func (w *ServerInterfaceWrapper) RunS3AthenaQueryTemplate(ctx echo.Context) error {
	var err error

	ctx.Set(Sigv4Scopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.RunS3AthenaQueryTemplate(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(baseURL+"/athena/run_query_template", wrapper.RunAthenaQueryTemplate)
	router.POST(baseURL+"/athena/run_s3_query_template", wrapper.RunS3AthenaQueryTemplate)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xWTW8bNxD9KwTro+SVo/ayN+VQIGiLupaBHIxAGO2OdhlTJE0OJSvG/vdiSH1GKzsN",
	"kFN60mo5HM578x5nX2Rll84aNBRk+SJD1eIS0uNdNBNq0cA/Ef3mHpdOA+EdPkUMxAHOW4eeFKZwSLHn",
	"7ysg0LaJyH9o41CWMpBXppHdQNZAMIfQv7i2/rHxNrqe1W4gPT5F5bGW5cPRKUc5jzN8Guwy2PlnrIjz",
	"O/CwREIfjg44LD8x7hltgb9dw1G6s82DHT99dVxiOjhrMjWnlObc+IxVJGXNTNW99H0dFqgfBqMIUdPM",
	"AbVvw+w5/dJZp5kvQJ+Of26ZhfHsXGmn4OaxekTqLf4RN2+Xvd2fo89LfE3H59W9ImVGg1X0ijZTvkhy",
	"9UE1q1/5QRlZyhahRi8H0sCS904itdarL8C6kfuU4NQfuJED+TyEJXyxZghONUC4hs0QIrW7uHWYpvwd",
	"n67MwvJJNYbKK5dSlnJy+0GsW1W1wnm7UjUGwc3jfxWGoEwjuIMLbdeiRe0yclKk8bt3r9CHfPrN9eh6",
	"xK2yDg04JUs5Tq9YGdQmiopMaeGj6RODzU44RXUXTRAgUrjYhQtrRLaTAFMLjxS9CYJaFNmKXBtLK9H9",
	"oc55egwosyYw0HtbJ4lV1hCaVAg4p1WVUhSfA1ezmxz8dOVxIUv5S3EYLcV2rhSvD5XUw1OU9y2KgyAH",
	"B6AML7MmaiRQOshjGZOPmG+2dIkmlt+NRj8cyPbOvoAkN8uDESFWrJ5F1HpzYhxZPuwt8/CpY5NBE9iX",
	"B9v1eUIZwia3lWtvidxfSK3lFt/+Pb1PcguBWm9j077HFlbKellKg6vkx4OhZs7bZ/Ze9Ipz/W7Kchrn",
	"vOhNefUy+Tgty1vwpPi0rjxUsVu8wyataFjOayhZ58W70c1vw9F4OL4pFtFUvDUUVy+ZxY9bB02c+jPt",
	"uZ543q9WWCizsrlHgXntBid26b8+/4NjsrdVENpCjbVYeLsU0/H3Oal3mP04L706O7/BTWEs8t39v51+",
	"Wjt1e0rO5mbWw366eeSm1GKv+nAY41s2uwt0bvU/XIFWNVBiCrSW3xidP/205p/ty53Ms6VYn4Ovl26P",
	"PrySgLvu3wAAAP//DoKFzPAMAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
